language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="40954b0a-1a6f-4c7e-b627-e013d8c915b0"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - foril2n1@rambler.ru
    on_success: never # default: change
    on_failure: always # default: always

# Start PostgreSQL
services:
  - postgresql

# Create a database
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres